<html>
<head>
    <h2>University of Stirling: MATPMD1 Statistics for Data Science</h2>
    <h3>Intro: Let's Get Started with R programming
    </h3>  
    <h4>Note: this markup was written using html tags</h4>
    <p> #for more info visit W3Schools: <a href="https://www.w3schools.com/r/"> Click me!</a> </p>
</head>

## "Hello world" and R variable declaration
   

In [1]:
### Short script to test if running script from with Jupyter R notebook works

testString <- "Hello World"      #this is how you declare variables in r using "<-"
print(testString)                # print in R

[1] "Hello World"


In [2]:
# I am an R comment (similar to python)  #Note: there is no syntax for multiline comment in R
"hello world"                          #this is an r string
5+5                                    #this is an r computation
name <- "malik"                        #declaring a variable name
age <- 23
print(name)                             #print variable
print(age)

[1] "hello world"

[1] 10

[1] "malik"
[1] 23


## Concatenate Elements
### You can also concatenate, or join, two or more elements, by using the "paste()" function.

In [3]:
text <- "awesome"

paste("R is", text)                     #paste function in r
paste(name, 'is', age, 'years', text)   #use 'paste' inplace of 'print' to concat strings in r

[1] "R is awesome"

[1] "malik is 23 years awesome"

In [4]:
# Multi Variable:
# R allows you to assign the same value to multiple variables in one line

var1 <- var2 <- var3 <- "Orange"

# Print variable values
var1
var2
var3

[1] "Orange"

[1] "Orange"

[1] "Orange"

## R Data types:

In [5]:
# numeric:
    #  A numeric data type is the most common type in R, 
    #    and contains any number with or without a decimal, like: 10.5, 55, 787
x <- 10.5
class(x)                       #class function returns what class a variable is

# integer:
    #  Integers are numeric data without decimals. This is used when you are certain that you will never create a 
    #   variable that should contain decimals(i.e no floats). The decimals are capped at a Billion
    #     To create an integer variable, you must use the letter L after the integer value
x <- 1000L
class(x)

# complex:
    #   A complex number is written with an "i" as the imaginary part
x <- 9i + 3
class(x)

# character/string
x <- "R is exciting"
class(x)

# logical/boolean : TRUE OR FALSE
x <- TRUE
y <- FALSE
class(x)
class(y)

#You can also convert from one Datatype to another using "as.type() fuction like so"
t = 10.5
a = as.integer(t)
class(t)
class(a)


[1] "numeric"

[1] "integer"

[1] "complex"

[1] "character"

[1] "logical"

[1] "logical"

[1] "numeric"

[1] "integer"

## Common R maths operators/functions:

In [6]:
10+5             #Addition
50-3             #subtraction
40*4             #Multiply
10/2             #division
2^4              #Exponent
5%%2              #modulus i.e remainder from division
100.50 %/% 2.40   #Integer Division (always returns a decimal value)
sqrt(64)          #square root

max(5, 10, 15)             #find the maximum

min(5, 10, 15)              #find the minimum

abs(-2.54)             #return the absolute(positive) value

ceiling(1.4)           #The ceiling() function rounds a number upwards to its nearest integer


floor(1.4)             #the floor() function rounds a number downwards to its nearest integer
        

[1] 15

[1] 47

[1] 160

[1] 5

[1] 16

[1] 1

[1] 41

[1] 8

[1] 15

[1] 5

[1] 2.54

[1] 2

[1] 1

In [7]:
#This is a preview as to how we run For loops in R

for (x in 1:10) {                           # unlike python you store the instruction inside curly brackets
  print(x)                                  # Also index start at '1' and not '0' like it would in python
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


# String Formating:

In [8]:
# assign a multiline string to a variable like this
str <- "Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."

str # print the value of str

# Note: that R will add a "\n" at the end of each line break. 
    #This is called an escape character, and the n character indicates a new line

# If you want the line breaks to be inserted at the same position as in the code, use the "cat()"" function
cat(str)

# Use the 'nchar()' function to return no of char in a string
nchar(str)

# Use the grepl() function to check if a character or a sequence of characters are present in a string
str <- "Hello World!"

grepl("H", str)    #returns true or false value
grepl("Hello", str)
grepl("X", str)

# use paste() mentioned previously to combine two or more strings
paste(name, str, age)

#use escape char (\) to insert double qupte in a string:
str <- "We are the so-called \"Vikings\", from the north."

str
cat(str)  #use cat to prevent output from printing (\)

# Other escape characters in R includes
#     \\	Backslash
#     \n	New Line
#     \r	Carriage Return
#     \t	Tab
#     \b	Backspace

[1] "Lorem ipsum dolor sit amet,\nconsectetur adipiscing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna aliqua."

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.

[1] 123

[1] TRUE

[1] TRUE

[1] FALSE

[1] "malik Hello World! 23"

[1] "We are the so-called \"Vikings\", from the north."

We are the so-called "Vikings", from the north.

## Operators in R:

In [9]:
# R Assignment Operators::: (they generally all do the same thing)
my_var <- 3

my_var <<- 3              # But this is a global assigner
                          # A global variable is a variable that can be used inside and outside a function
                          # Functions usually can only see variable declared inside of them
                          # But a global variable allows complete access
3 -> my_var

3 ->> my_var

my_var # print my_var

# R Comparison Operators
10 > 9       # TRUE because 10 is greater than 9
10 == 9      # FALSE because 10 is not equal to 9
10 < 9       # FALSE because 10 is greater than 9
10 == (2*5)  # TRUE because 10 is equal(or compared) to 10
10 >= 2.5    # Greater than or equals too
50 <= 100    # Less than or equals to
50 != 100    #not equals too

#R Logical Operators:
        ##Logical operators are used to combine conditional statements
# & :- Element-wise Logical AND operator. It returns TRUE if both elements are TRUE
# && :- Logical AND operator - Returns TRUE if both statements are TRUE
# | :- Elementwise- Logical OR operator. It returns TRUE if one of the statement is TRUE
# || :- Logical OR operator. It returns TRUE if one of the statement is TRUE.
# ! :- Logical NOT - returns FALSE if statement is TRUE

# Others::
x <- 1:10    #create a series
y <- 1:50
print(x)

x %in% y            #Find out if an element belongs to a vector with (%in%)

#x <- Matrix1 %*% Matrix2            #Matrix multiplication using (%*%)


[1] 3

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

 [1]  1  2  3  4  5  6  7  8  9 10


[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

## Conditional Statements IF ELSE:

In [10]:
# If : 
    ## [Note:R uses curly brackets { } to define the scope in the code]
a <- 33
b <- 200

if (b > a) {
  print("b is greater than a")
}

# Else If:
## The else if keyword is R's way of saying "if the previous conditions were not true, then try this condition"
a <- 33
b <- 33

if (b > a) {
  print("b is greater than a")
} else if (a == b) {
  print ("a and b are equal")
}

# If Else:
    #The else keyword catches anything which isn't caught by the preceding conditions
a <- 200
b <- 33

if (b > a) {
  print("b is greater than a")
} else if (a == b) {
  print("a and b are equal")
} else {
  print("a is greater than b")
}


# Nested If Statements:
## You can also have if statements inside if statements, this is called nested if statements.
x <- 41

if (x > 10) {
  print("Above ten")
  if (x > 20) {
    print("and also above 20!")
  } else {
    print("but not above 20.")
  }
} else {
  print("below 10.")
}


# (AND) --- (OR)::
# The '&' symbol (and) is a logical operator, and is used to combine conditional statements:
a <- 200
b <- 33
c <- 500

if (a > b & c > a){
  print("Both conditions are true")
}

# The '|' symbol (or) is a logical operator, and is used to combine conditional statement:
a <- 200
b <- 33
c <- 500

if (a > b | a > c){
  print("At least one of the conditions is true")
}


[1] "b is greater than a"
[1] "a and b are equal"
[1] "a is greater than b"
[1] "Above ten"
[1] "and also above 20!"
[1] "Both conditions are true"
[1] "At least one of the conditions is true"


## R While loops:
### With the while loop we can execute a set of statements as long as a condition is TRUE

In [11]:
# While statement
i <- 1     
while (i < 6) {              #Print i as long as i is less than 6:
  print(i)
  i <- i + 1
}

# Break:
    # With the break statement, we can stop the loop even if the while condition is TRUE
i <- 1
while (i < 6) {
  print(i)
  i <- i + 1
  if (i == 4) {                  #the loop stop after printing i = 3
    break
  }
}

# Next:
    # With the next statement, we can skip an iteration without terminating the loop:
i <- 0
while (i < 6) {
  i <- i + 1
  if (i == 3) {                   #the loop doesnt print i = 3
    next
  }
  print(i)
}

#example:
dice <- 1
while (dice <= 6) {
  if (dice < 6) {
    print("No Yahtzee")
  } else {
    print("Yahtzee!")
  }
  dice <- dice + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 1
[1] 2
[1] 3
[1] 1
[1] 2
[1] 4
[1] 5
[1] 6
[1] "No Yahtzee"
[1] "No Yahtzee"
[1] "No Yahtzee"
[1] "No Yahtzee"
[1] "No Yahtzee"
[1] "Yahtzee!"


## For Loops:
### A for loop is used for iterating over a sequence

In [12]:
# Ex1:
for (x in 1:10) {
  print(x)
}

# Ex2:
fruits <- list("apple", "banana", "cherry")  #declaring a list in R

for (x in fruits) {
  print(x)
}

# Ex3:
dice <- c(1, 2, 3, 4, 5, 6)                      #declaring a vector in R 

for (x in dice) {
  print(x)
}


# Break in R for loops:
fruits <- list("apple", "banana", "cherry")

for (x in fruits) {
  if (x == "cherry") {              #printing stops at banana
    break
  }
  print(x)
}


# Next in R for loops:
fruits <- list("apple", "banana", "cherry")

for (x in fruits) {
  if (x == "banana") {
    next                            #print skips banana
  }
  print(x)
}


# Ex4:
dice <- 1:6

for(x in dice) {
  if (x == 6) {
    print(paste("The dice number is", x, "Yahtzee!"))
  } else {
    print(paste("The dice number is", x, "Not Yahtzee"))
  }
}


# Nested For loops in R:
adj <- list("red", "big", "tasty")

fruits <- list("apple", "banana", "cherry")
  for (x in adj) {
    for (y in fruits) {
      print(paste(x, y))
  }
}


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] "apple"
[1] "banana"
[1] "cherry"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] "apple"
[1] "banana"
[1] "apple"
[1] "cherry"
[1] "The dice number is 1 Not Yahtzee"
[1] "The dice number is 2 Not Yahtzee"
[1] "The dice number is 3 Not Yahtzee"
[1] "The dice number is 4 Not Yahtzee"
[1] "The dice number is 5 Not Yahtzee"
[1] "The dice number is 6 Yahtzee!"
[1] "red apple"
[1] "red banana"
[1] "red cherry"
[1] "big apple"
[1] "big banana"
[1] "big cherry"
[1] "tasty apple"
[1] "tasty banana"
[1] "tasty cherry"


## R functions:
### A function is a block of code which only runs when it is called.

#### You can pass data, known as parameters, into a function. A function can return data as a results

### Parameters or Arguments?
#### The terms "parameter" and "argument" can be used for the same thing: information that are passed into a function. From a function's perspective: 
#####  -A parameter is the variable listed inside the parentheses in the function definition. 
##### - An argument is the value that is sent to the function when it is called.

In [13]:
# Before we begin, DO! Note! that in R fuction are stored/defined in variables as shown below
    ## THis is completely different from how its done in python:

my_function <- function() { # create a function with the name my_function
  print("Hello World!")
}
my_function()            #calling the function in R

# In py it would be this way  def my_function(): 
#                                 print("Hello world")
#                             my_function()      


# Parameters in R function
my_function <- function(fname) {
  paste(fname, "Griffin")
}

my_function("Peter")
my_function("Lois")
my_function("Stewie")


# Default Parameter Value
    #The following example shows how to use a default parameter value.
        #If we call the function without an argument, it uses the default value:

my_function <- function(country = "Norway") {
  paste("I am from", country)
}

my_function("Sweden")
my_function("India")
my_function() # will get the default value, which is Norway
my_function("USA")


# Return() in R fuctions:
    #return() lets you store the result of your function in memory, for futher use

my_function <- function(x) {
  return (5 * x)
}

print(my_function(3))
print(my_function(5))
print(my_function(9))
a <- my_function(3) + my_function(5)
print(a)


# NEsted Fuctions: A functio called within another function or a function wriiten within a function

# EX1: calling a function within another function
Nested_function <- function(x, y) {
  a <- x + y
  return(a)
}

Nested_function(Nested_function(2,2), Nested_function(3,3))

# EX2: Write a function within a function
Outer_func <- function(x) {
  Inner_func <- function(y) {
    a <- x + y
    return(a)
  }
  return (Inner_func)
}
output <- Outer_func(3)  #first we call the outer_fucn into a new variable 'output'
                           # this is so, to be able to later call the inner_func()
output(5)            #now we can call the inner function with the desired value of "y", which in this case is 5


# Recursion:
    # R also accepts function recursion, which means a defined function can call itself.
tri_recursion <- function(k) {
  if (k > 0) {
    result <- k + tri_recursion(k - 1)        #good way to think about this problem is to start solving at the lowest value
    print(result)                             # i.e when k=o and k =1 then work your way up from ther
  } else {                                    #this is the art of thinking recursively
    result = 0                                #visualize your problem at the smallest scale possiblie first!!!
    return(result)
  }
}
tri_recursion(6)

[1] "Hello World!"


[1] "Peter Griffin"

[1] "Lois Griffin"

[1] "Stewie Griffin"

[1] "I am from Sweden"

[1] "I am from India"

[1] "I am from Norway"

[1] "I am from USA"

[1] 15
[1] 25
[1] 45
[1] 40


[1] 10

[1] 8

[1] 1
[1] 3
[1] 6
[1] 10
[1] 15
[1] 21


# R Data Structures:
## Vectors, List, Matrices, Array, Dataframes, Factors

### Visit : https://www.w3schools.com/r/r_lists.asp for more info...

In [14]:
# Vectors in R:
    # A vector is simply a list of items that are of the same type.
fruits <- c("banana", "apple", "orange", "pawpaw", "lemon") #use vector function c()
numbers <- c(1, 2, 3)
numbers0 <- 1:10                # Vector with numerical values in a sequence
numbers1 <- 1.5:6.5            # Vector with numerical decimals in a sequence
numbers2 <- 1.5:6.3           # Vector with numerical decimals in a sequence where the last element is not used
log_values <- c(TRUE, FALSE, TRUE, FALSE) # Vector of logical values

fruits
numbers
numbers0
numbers1
numbers2
log_values

length(fruits)        # find out how many items a vector has, use the length() function

sort(fruits)         # sort items in a vector alphabetically or numerically, use the sort() function:

    # Access Vectors
fruits[1]         # Access the vector items by referring to its index number inside brackets []
fruits[c(1, 3)]   # Access multiple elements by referring to different index positions with the c() function
fruits[c(-1)]     # Access all items except for the first item
fruits[1] <- "pear"   # Change item "banana" to "pear"
print(fruits)

    # Repeat Vectors
repeat_each <- rep(c(1,2,3), each = 3) # To repeat vectorsindividually, use the rep() function:
repeat_each
repeat_times <- rep(c(1,2,3), times = 3) # repeart sequence orderly
repeat_times
repeat_indepent <- rep(c(1,2,3), times = c(5,2,1)) #Repeat each value independently:
repeat_indepent

    # Generate Sequence
numbers <- seq(from = 0, to = 100, by = 20) # make bigger or smaller steps in a sequence, use the seq() function
numbers

numbers <- 1:10
numbers

[1] "banana" "apple"  "orange" "pawpaw" "lemon"

[1] 1 2 3

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1.5 2.5 3.5 4.5 5.5 6.5

[1] 1.5 2.5 3.5 4.5 5.5

[1]  TRUE FALSE  TRUE FALSE

[1] 5

[1] "apple"  "banana" "lemon"  "orange" "pawpaw"

[1] "banana"

[1] "banana" "orange"

[1] "apple"  "orange" "pawpaw" "lemon"

[1] "pear"   "apple"  "orange" "pawpaw" "lemon" 


[1] 1 1 1 2 2 2 3 3 3

[1] 1 2 3 1 2 3 1 2 3

[1] 1 1 1 1 1 2 2 3

[1]   0  20  40  60  80 100

[1]  1  2  3  4  5  6  7  8  9 10

In [38]:
# Lists in R:
    # A list in R can contain many different data types inside it. 
        # A list is a collection of data which is ordered and changeable.

thislist <- list("apple", "banana", "cherry")    #use the list() function
thislist   #print the list

# access items in a list
thislist <- list("apple", "banana", "cherry")
thislist[1]

# To change the value of a specific item, refer to the index number:
thislist[1] <- "blackcurrant"

# To find out how many items a list has, use the length() function:
length(thislist)

# CHeck if item is present in a list, use the %in% operator
"apple" %in% thislist

# use append() function To add an item to the end of the list:
append(thislist, "orange")


# To add an item to the right of a specified index, add "after=index number" in the append() function:
thislist <- list("apple", "banana", "cherry")
append(thislist, "orange", after = 2)


# Remove Item from list by index :
newlist <- thislist[-1]
newlist


# Obtain range of values in list by specifying where to start and where to end the range, by using the ':'
thislist <- list("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
thislist[2:5]


# Loop through a list:
for (x in thislist) {
  print(x)
}


# Join lists using concat c() 
list1 <- list("a", "b", "c")
list2 <- list(1,2,3)
list3 <- c(list1,list2)

list3


[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[1]]
[1] "apple"

[1] 3

[1] FALSE

[[1]]
[1] "blackcurrant"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[4]]
[1] "orange"

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

[[4]]
[1] "cherry"

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

[[3]]
[1] "orange"

[[4]]
[1] "kiwi"

[1] "apple"
[1] "banana"
[1] "cherry"
[1] "orange"
[1] "kiwi"
[1] "melon"
[1] "mango"


[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

In [31]:
# MAtrices in R:
    # A matrix is a two dimensional data set with columns and rows.
     # matrix can be created with the matrix() function. 
      # Specify the nrow and ncol parameters to get the amount of rows and columns
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)
thismatrix

thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix
# Note: the c() is used to concatenate items together


# Access Matrix
thismatrix[1, 2]        # 1st no is the row pos 2nd is the column pos

thismatrix[2,]         # Access entire row

thismatrix[,2]         # Access entire column

thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[c(1,2),]     # access more than 1 row

thismatrix[, c(1,2)]    # access more than 1 column

thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix


# Adding Rows and Columns to a matrix 
    # use cbind() function to add additional COLUMNS to a matrix:
    # cbind() takes 2 args the original matrix and new column additions
newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))
newmatrix         #Print the new matrix

    # Use the rbind() function to add additional rows in a Matrix:
    # rbind() takes 2 args the original matrix and new row additions
newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))
newmatrix         #Print the new matrix


# Use the -c() function to remove rows and columns in a Matrix:
thismatrix <- thismatrix[-c(1), -c(1)]           # T/N: 'c' is not same as '-c'
thismatrix


# To find out if a specified item is present in a matrix, use the %in% operator:
"apple" %in% thismatrix          #returns bool True/False


# Use the dim() function to find the amount of rows and columns in a Matrix:
thismatrix
dim(thismatrix)


# Use the length() function to find the dimension of a Matrix:
length(thismatrix)


# loop through a Matrix using a for loop. The loop will start at the first row, moving right:
for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}


# Combine two or more matrices using rbind() or cbind():::
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

    # Adding it as a rows 'rbind()'
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

    # Adding it as a columns 'cbind()':
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[1] "cherry"

[1] "banana" "orange"

[1] "cherry" "orange"

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]      [,3]  [,4]      
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry 
[3,] cherry pineapple fig   raspberry

[,1]       [,2]      [,3]     
[1,] apple      orange    pear     
[2,] banana     grape     melon    
[3,] cherry     pineapple fig      
[4,] strawberry blueberry raspberry

[,1]      [,2] 
[1,] grape     melon
[2,] pineapple fig

[1] FALSE

[,1]      [,2] 
[1,] grape     melon
[2,] pineapple fig

[1] 2 2

[1] 4

[1] "grape"
[1] "melon"
[1] "pineapple"
[1] "fig"


[,1]   [,2]      
[1,] apple  cherry    
[2,] banana grape     
[3,] orange pineapple 
[4,] mango  watermelon

[,1]   [,2]   [,3]   [,4]      
[1,] apple  cherry orange pineapple 
[2,] banana grape  mango  watermelon

# Data Frames in R...

In [60]:
# Data Frames in R::
    # Data Frames are data displayed in a format as a table.
    # Data Frames can have different types of data inside it. While the first column can be character, 
    #  the second and third can be numeric or logical. However, each column should have the same type of data.

# Use the data.frame() function to create a data frame:
Data_Frame <- data.frame(parties = c("Tory","Labour","Lib-Dem", "Other"),
                       A = c(110,11,37,2),
                       B = c(420,99,237,8),
                       C1 = c(321,119,143,12),
                       C2 = c(353,363,205,9),
                       D = c(183,286,134,6))
Data_Frame


# Use the summary() function to summarize the data from a Data Frame:
summary(Data_Frame)


# Access: We can use single brackets [ ], double brackets [[ ]] or $ to access columns from a data frame:

Data_Frame[1]        # Select the 1st column in the dataframe

Data_Frame[["A"]]

Data_Frame$C2


# Use the rbind() function to add new rows in a Data Frame:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

    # Add a new row
New_row_DF <- rbind(Data_Frame, c("Strength", 110, 110))
New_row_DF


# Use the cbind() function to add new columns in a Data Frame:
New_col_DF <- cbind(Data_Frame, Steps = c(1000, 6000, 2000))
New_col_DF


# Use the -c() function to remove rows and columns in a Data Frame:
Data_Frame_New <- Data_Frame[-c(1), -c(1)]
Data_Frame_New


# Use the dim() function to find the amount of rows and columns in a Data Frame:
dim(Data_Frame)


# use the ncol() function to find the number of columns and nrow() to find the number of rows:
ncol(Data_Frame)
nrow(Data_Frame)


#Use the length() function to find the number of columns in a Data Frame (similar to ncol()):
length(Data_Frame)


# Combine 2 or more Dataframes 'vertically' with rbind():
Data_Frame1 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame2 <- data.frame (
  Training = c("Stamina", "Stamina", "Strength"),
  Pulse = c(140, 150, 160),
  Duration = c(30, 30, 20)
)

New_Data_Frame <- rbind(Data_Frame1, Data_Frame2)
New_Data_Frame


# Combine 2 or more Dataframes 'Horizontally' with cbind():
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1



parties A   B   C1  C2  D  
1 Tory    110 420 321 353 183
2 Labour   11  99 119 363 286
3 Lib-Dem  37 237 143 205 134
4 Other     2   8  12   9   6

    parties        A                B                C1               C2       
 Labour :1   Min.   :  2.00   Min.   :  8.00   Min.   : 12.00   Min.   :  9.0  
 Lib-Dem:1   1st Qu.:  8.75   1st Qu.: 76.25   1st Qu.: 92.25   1st Qu.:156.0  
 Other  :1   Median : 24.00   Median :168.00   Median :131.00   Median :279.0  
 Tory   :1   Mean   : 40.00   Mean   :191.00   Mean   :148.75   Mean   :232.5  
             3rd Qu.: 55.25   3rd Qu.:282.75   3rd Qu.:187.50   3rd Qu.:355.5  
             Max.   :110.00   Max.   :420.00   Max.   :321.00   Max.   :363.0  
       D        
 Min.   :  6.0  
 1st Qu.:102.0  
 Median :158.5  
 Mean   :152.2  
 3rd Qu.:208.8  
 Max.   :286.0  

parties
1 Tory   
2 Labour 
3 Lib-Dem
4 Other

[1] 110  11  37   2

[1] 353 363 205   9

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Strength 110   110

Training Pulse Duration Steps
1 Strength 100   60       1000 
2 Stamina  150   30       6000 
3 Other    120   45       2000

Pulse Duration
2 150   30      
3 120   45

[1] 3 3

[1] 3

[1] 3

[1] 3

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Stamina  140   30      
5 Stamina  150   30      
6 Strength 160   20

Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300     
2 Stamina  150   30       6000  400     
3 Other    120   45       2000  300

# Arrays in R....

In [23]:
# Arrays in R::
    # Compared to matrices, arrays can have more than two dimensions.
    # Use the array() function to create an array, and the 'dim' parameter to specify the dimensions:

# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

# An array with more than one dimension: 
    #Note: array() takes 2 args 'the data' and 'dimension' specification
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray

# How does dim=c(4,3,2) work?
# The first and second number in the bracket specifies the amount of 'rows' and 'columns'.
# The last number in the bracket specifies how many dimensions we want.
# You can visualize a 2d array as a double matrix stack and a 3d array as a triple matrix stack
#  i.e matrix of a defined  row and column stack upon each other. 


# You can access the array elements by referring to the index position. 
    # You can use the [] brackets to access the desired elements from an array:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

multiarray[2, 3, 2] #here weve requested for the data contained in row=2 col=3 on matrix 1 array



# You can also, access the whole row or column from a matrix in an array, by using the c() function:
thisarray <- c(1:24)

    # Access all the items from the first row from matrix one 
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[c(1),,1]
multiarray[c(1),,2]    #from matrix two

    # Access all the items from the first column from matrix one 
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[,c(1),1]
multiarray[,c(1),2]    #from matrix two


# Check if an Item Exists in an array, use the %in% operator:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray    #return bool T/F


# Use the dim() function to find the amount of rows and columns in an array:
dim(multiarray)


# Use the length() function to find the dimension of an array:
length(multiarray)


# You can loop through the array items by using a for loop:
for (x in multiarray) {
    print(x)
}

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

[1] 22

[1] 1 5 9

[1] 13 17 21

[1] 1 2 3 4

[1] 13 14 15 16

[1] TRUE

[1] 4 3 2

[1] 24

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24


In [15]:
# Factors in R:::
    # Factors are used to categorize data thus returning distince values(levels) for the data representation.
    # Examples of factors are: 'Demography: Male/Female' , 'Music: Rock, Pop, Classic'
    # Factors can created using the factor() function and add a 'vector' as argument:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
music_genre


#TO only print levels in a factor use levels()
levels(music_genre)


# You can also set the levels, by adding the levels argument inside the factor() function:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Other"))
levels(music_genre)


# Use the length() function to find out how many items there are in the factor:
length(music_genre)


# To Access the items in a factor, refer to the index number, using [] brackets:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
music_genre[3]


# To change the value of a specific item, refer to the index number:
    # Note: that you cannot change the value of a specific 
    #        item if it is not already specified in the factor.
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
music_genre[3] <- "Pop"
music_genre[3]

music_genre[3] <- "Opera"    #results in error
music_genre[3]


# However, if you have already specified it inside the 'levels' argument, it will work:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Opera"))
music_genre[3] <- "Opera"
music_genre[3]

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

[1] "Classic" "Jazz"    "Pop"     "Rock"

[1] "Classic" "Jazz"    "Pop"     "Rock"    "Other"

[1] 8

[1] Classic
Levels: Classic Jazz Pop Rock

[1] Pop
Levels: Classic Jazz Pop Rock

Warning message in `[<-.factor`(`*tmp*`, 3, value = "Opera"):
"invalid factor level, NA generated"


[1] <NA>
Levels: Classic Jazz Pop Rock

[1] Opera
Levels: Classic Jazz Pop Rock Opera

<body>
    <h2>The End</h2>
    <p>Great, it looks like you're all set up and ready to Explore Statistical Analysi in R.
    </p>
</body>